version: '3.7'
services:
   client:
      build:
         context: ./frontend
         dockerfile: DockerFile
      tty: true
      ports:
         - "3000:3000"
      volumes:
         - ./frontend:/app
         - /app/node_modules

   mongodb:
      image: mongo
      container_name: mongo
      restart: unless-stopped
      command: mongod --auth
      environment:
         MONGO_INITDB_ROOT_USERNAME: "admin"
         MONGO_INITDB_ROOT_PASSWORD: "adminpassword"
         MONGO_INITDB_DATABASE: smartDB
         MONGODB_DATA_DIR: /data/db
      volumes:
         - mongodbdata:/data/db
      networks:
         - backend

   api:
      build: 
         context: ./backend
         dockerfile: DockerFile
      command: gunicorn --bind 0.0.0.0:5000 app:app
      ports:
         - "5000:5000"
      environment:
         MONGODB_HOST: mongodb
         MONGODB_USERNAME: "sathwik"
         MONGODB_PASSWORD: "kelavi"
      volumes:
         - appdata:/var/www/
      depends_on: 
         - mongodb
      networks:
         - frontend
         - backend

networks:
   frontend:
      driver: bridge
   backend:
      driver: bridge
volumes:
   mongodbdata:
      driver: local
   appdata:
      driver: local