# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Recommendation.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Recommendation.proto',
  package='recommendation',
  syntax='proto3',
  serialized_options=b'\n\026io.grpc.recommendationB\016RecommendationP\001\242\002\003RMD',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14Recommendation.proto\x12\x0erecommendation\x1a\x1bgoogle/protobuf/empty.proto\"\xe6\x01\n\rResponseItems\x12\x0f\n\x07uniq_id\x18\x01 \x01(\t\x12\x14\n\x0cproduct_name\x18\x02 \x01(\t\x12\x1d\n\x15product_category_tree\x18\x03 \x01(\t\x12\x0b\n\x03pid\x18\x04 \x01(\t\x12\x14\n\x0cretail_price\x18\x05 \x01(\x01\x12\x18\n\x10\x64iscounted_price\x18\x06 \x01(\x01\x12\r\n\x05image\x18\x07 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x08 \x01(\t\x12\x16\n\x0eproduct_rating\x18\t \x01(\x01\x12\x16\n\x0eoverall_rating\x18\n \x01(\x01\x32P\n\x08Genrator\x12\x44\n\tSendItems\x12\x16.google.protobuf.Empty\x1a\x1d.recommendation.ResponseItems\"\x00\x42\x30\n\x16io.grpc.recommendationB\x0eRecommendationP\x01\xa2\x02\x03RMDb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_RESPONSEITEMS = _descriptor.Descriptor(
  name='ResponseItems',
  full_name='recommendation.ResponseItems',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='uniq_id', full_name='recommendation.ResponseItems.uniq_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='product_name', full_name='recommendation.ResponseItems.product_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='product_category_tree', full_name='recommendation.ResponseItems.product_category_tree', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pid', full_name='recommendation.ResponseItems.pid', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='retail_price', full_name='recommendation.ResponseItems.retail_price', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='discounted_price', full_name='recommendation.ResponseItems.discounted_price', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='image', full_name='recommendation.ResponseItems.image', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='description', full_name='recommendation.ResponseItems.description', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='product_rating', full_name='recommendation.ResponseItems.product_rating', index=8,
      number=9, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='overall_rating', full_name='recommendation.ResponseItems.overall_rating', index=9,
      number=10, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=300,
)

DESCRIPTOR.message_types_by_name['ResponseItems'] = _RESPONSEITEMS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ResponseItems = _reflection.GeneratedProtocolMessageType('ResponseItems', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSEITEMS,
  '__module__' : 'Recommendation_pb2'
  # @@protoc_insertion_point(class_scope:recommendation.ResponseItems)
  })
_sym_db.RegisterMessage(ResponseItems)


DESCRIPTOR._options = None

_GENRATOR = _descriptor.ServiceDescriptor(
  name='Genrator',
  full_name='recommendation.Genrator',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=302,
  serialized_end=382,
  methods=[
  _descriptor.MethodDescriptor(
    name='SendItems',
    full_name='recommendation.Genrator.SendItems',
    index=0,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_RESPONSEITEMS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_GENRATOR)

DESCRIPTOR.services_by_name['Genrator'] = _GENRATOR

# @@protoc_insertion_point(module_scope)
